version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./modelink_front:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
